name: LearningGithubActions
on:
  push: 
      branches: 
        - main
jobs:
   build:
        name: MY First JOb
        runs-on: ubuntu-latest
        permissions:
          security-events: write
          actions: read
          contents: read
        steps:
          - name: check out the code
            uses: actions/checkout@v4
          - name: Hello how are you
            run:  echo "Hello how are you"
          - name: List environment variable
            run:  printenv
          - name: Welcome to project 
            run:  echo "welcome to project learning githubaction"
          - name: check the internet
            run:  curl -I https://www.google.com
          - name: Intialize the CodeQL
            uses: github/codeql-action/init@v3
            with:
              languages: java
          
          - name: Analyze the code
            uses: github/codeql-action/analyze@v3
         
    


